### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by Jabbo16** [Plankton555/SSCAIT-ObserverModule#1]
Hey, I found this repo and ported the Observer to Java to use it the with latest BWMirror API.

With this project having no license I cant really publish it open source on Github (can only use it for private use).

Adding an open source license would allow me to publish my Java port of your code with the same license so other Java programmers using BWMirror would benefit for having an observer that they could add to their bots for easier testing and managing of the game camera.

**Comment by Plankton555** [comment]
Hi! That's awesome!

I was apparantly a bit too lazy when I uploaded the code to Github and forgot the license. Will fix it asap.

**Comment by certicky** [comment]
Hi Jabbo16. Just wanted to kindly ask you to reference our paper about the observer, when you use it: [https://arxiv.org/abs/1505.00278](https://arxiv.org/abs/1505.00278) 

Anyway, I'm glad to hear you'll use it in BWMirror. Good luck with it!

**Comment by Plankton555** [comment]
Added the license :)
Happy coding!

**Comment by Jabbo16** [comment]
@Plankton555 @certicky Done!

https://github.com/Jabbo16/SSCAIT-ObserverModule-BWMirror

I hope I didnt forget anything...
